name: benckmark

on:
  push:
    branches: [main]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.2"
      - run: "GOOS=js GOARCH=wasm go build -o dist/main.wasm main.go"
      - run: "deno run --allow-read --no-check ./benchmark/benchmark.ts"
